name: JavaEE Support
title: Navigate your way through EE via Tests
org: JavaEE Samples
issue_tracker: 'https://github.com/javaee-samples/javaee7-samples/issues'
base_url: ''
profiles:
  development:
    base_url: ''
    deploy: nil # force development as the default
  production:
    base_url: 'http://javaee.support'
    fingerprint_assets: true
    minify: true
    google_analytics:
      account: UA-18727998-5
    deploy:
      host: github_pages
      branch: master
      repository: upstream
